#!/usr/bin/env python

import subprocess
import os
import sys
import json
import urllib
from bitbucket import BitbucketException, BitbucketCloudDriver, BitbucketServerDriver, set_build_status
from concourse import print_error
from helper import json_pp

config = json.loads(sys.stdin.read())

debug = config['source'].get('debug', False)

if debug:
    print_error("--DEBUG MODE--")

# Configuration vars
driver = config['source'].get('driver', 'Bitbucket Server')

build_status = config['params'].get('build_status', config['params'].get('state'))

if driver == 'Bitbucket Server':
    driver = BitbucketServerDriver(config, debug)
elif driver == 'Bitbucket Cloud':
    driver = BitbucketCloudDriver(config, debug)
else:
    print_error("Invalid driver, must be: 'Bitbucket Server' or 'Bitbucket Cloud'")
    exit(1)


# The build status can only be one of these things
if driver == 'Bitbucket Server':
    if build_status not in ['INPROGRESS', 'SUCCESSFUL', 'FAILED']:
        print_error("Invalid build status, must be: INPROGRESS, SUCCESSFUL, or FAILED")
        exit(1)
else:
    if build_status not in ['INPROGRESS', 'SUCCESSFUL', 'FAILED', 'STOPPED']:
        print_error("Invalid build status, must be: INPROGRESS, SUCCESSFUL, FAILED, or STOPPED")
        exit(1)

commit_hash = ''

if "commit_hash_file" in config["params"]:
    with open(os.path.join(sys.argv[1], config["params"]["commit_hash_file"]), "r") as fp:
        commit_hash = fp.readlines()[0].strip()
# Try and find out if it's a git or hg repo.
else:
    artifact_dir = "%s/%s" % (sys.argv[1], config['params'].get('repository', config['params'].get('repo')))
    if os.path.exists(os.path.join(artifact_dir, '.hg')):
        commit_hash = subprocess.check_output(
            ['hg', '-R', artifact_dir, 'log', '--rev', '.', '--template', '{node}']
        ).strip().decode()
    elif os.path.exists(os.path.join(artifact_dir, '.git')):
        commit_hash = subprocess.check_output(
            ['git', '-C', artifact_dir, 'rev-parse', 'HEAD']
        ).strip().decode()
    else:
        print_error("Cannot detect a repository.")
        exit(1)

if debug:
    print_error("Commit: " + str(commit_hash))

if "build_url_file" in config["params"]:
        with open(os.path.join(sys.argv[1], config["params"]["build_url_file"]), "r") as fp:
            build_url = fp.readlines()[0].strip()
else:
    if 'BUILD_PIPELINE_NAME' in os.environ:
        maybe_team = 'teams/{team}/'.format(team=os.environ['BUILD_TEAM_NAME']) if 'BUILD_TEAM_NAME' in os.environ else ''
        build_path = "{maybe_team}pipelines/{pipeline}/jobs/{jobname}/builds/{buildname}".format(
            maybe_team=maybe_team,
            pipeline=os.environ['BUILD_PIPELINE_NAME'],
            jobname=os.environ['BUILD_JOB_NAME'],
            buildname=os.environ['BUILD_NAME'],
        )
    else:
        build_path = 'builds/{build}'.format(
            build=os.environ['BUILD_ID']
        )

    build_url = "{url}/{path}".format(
        url=os.environ['ATC_EXTERNAL_URL'],
        path=urllib.quote(build_path)
    )

if debug:
    print_error("Build URL: " + str(build_url))

if "key" in config["params"]:
    key = config["params"]["key"]
else:
    key = os.environ.get("BUILD_JOB_NAME", 'one-off-build-{0}'.format(os.environ['BUILD_ID']))

if "name" in config["params"]:
    name = config["params"]["name"]
else:
    if 'BUILD_JOB_NAME' in os.environ:
        name = '{} #{}'.format(os.environ['BUILD_JOB_NAME'], os.environ['BUILD_NAME'])
    else:
        name = 'One-off build #{}'.format(os.environ['BUILD_ID'])

if "description_file" in config["params"]:
    with open(os.path.join(sys.argv[1], config["params"]["description_file"]), "r") as fp:
        description = fp.read()
else:
    description = "Concourse CI build, hijack as #{0}".format(os.environ["BUILD_ID"])

# Do the update.
try:
    set_build_status(
        commit_hash=commit_hash,
        build_status=build_status,
        key=key,
        name=name,
        url=build_url,
        description=description,
        debug=debug,
        driver=driver
    )

except BitbucketException as e:
    print_error(str(e))
    exit(1)

status = {"version": {"build_status": build_status}}

if debug:
    print_error("Returning to Concourse:\n" + json_pp(status))

print(json.dumps(status))
